= Website source layout

Considerations:

* Journal content may only be available to ACCU members.
* Large binaries should be kept out of the regular Git repo. Small ones are OK.
  So for the the purposes of journals, PDF and EPUB should be separate, but
  images can be in the main tree.
* Layout should be logical, clean, and it should be obvious to new maintainers or contributors
  where contributions should go.
* Website in repo under `accu.org`.
* There should be a top level build file in the repo.
** It will run the Hugo command line to generate the site content.
** If necessary (see <<_journal_indexes>>), this will generate all indexes,
   both overall journal indexes and individual issue indexes.
   Indexes will be generated in `.adoc` and  won't be checked in.
   This is so indexes can be regenerated if format changes.

== Basic rules

* All input files are in UTF-8.
** Old site files need conversion. `inconv` is your friend.
* We will use a static site generator, with AsciiDoc as the input format.
  Markdown is also popular, but there is no universal standard and it lacks a lot of the
  features of AsciiDoc. We would therefore risk locking ourselves in a particular generator's
  flavour of Markdown, and hence that generator.
** https://gohugo.io/[Hugo] is the current gorilla in the static site generator scene.
   It's won over previous frontrunners on (as far as I can tell) merit; it's fast, for one
   thing, though using AsciiDoc wrecks that advantage by needing to run everything
   through https://asciidoctor.org[AsciiDoctor].
   However, being pre-eminent means it has other advantages; a wide choice of free
   and payware themes and theming expertise, for one.
   There doesn't seem to me to be a good reason for not using Hugo.

== Journal directory structure

* Each journal issue to have its own directory.
** Directory named `content/journal/<journal name>/<year>/<month>`.
   Journal name and month will be lower case.
   Month will be first 3 characters of month name in English.
** Individual articles in a file named after the article title, once it has been lowercased,
   spaces replaced by `_` and all characters not in `[a-z0-9]` removed.
   Any newlines in article titles are replaced with spaces.
** Articles files are `.adoc`.
** Image files to be named with the article title (post previous processing) and a serial suffix
   and stored in the issue directory.
** Article files and image files are checked in to repo.
* `journal/<journal name>` to be a subrepo. This is so the subrepo can be stored
   in a private or public repo depending on the journal accessibility.
* For old articles with Xaraya ID, also generate an HTML redirect at `journals/index/<id>`.

File are named after the article title rather than the author to avoid
clashes when one author has multiple pieces per issue.

== Large binaries directory structure

* Each journal issue to have its own directory.
** Directory named `assets/journal/<journal name>/<year>/<month>`.
*** So everything under `assets` is in the same dir path as the journal content.
*** Mount `assets` under `accu.org/static` in the Hugo tree.
** PDF if present to be `<journal name>.pdf`.
** EPUB if present to be `<journal name>.epub`.
** Cover image if present to be `Cover.png/jpg`.

== Journal indexes

If possible, I want to handle all journal indexing using
https://gohugo.io/content-management/taxonomies/[Hugo taxonomies].
This means adding taxonomy data with outher metadata in Hugo fontmatter for each article.
For example, if we define taxonomies `journals`, `categories` and `contributors`. in
`config.toml`, given frontmatter like the following we can hopefully use the taxonomies
to generate indexes by author, journal, and article category

--------------------------------------------------
---
title: Afterwood
author: Chris Oldwood
date: 2018-02-01T16:13:46
draft: false
journals:
- Overload
month: February
year: 2018
aliases:
- /xaraya/journals/2461.html
categories:
- Process Topics
description: Can you code on paper in an interview? Chris Oldwood recounts his attempts to write a calendar.
number: 143
volume: 26
pages: 24
contributors: ['Oldwood, Chris']
---
= Afterwood
:author: Chris Oldwood
--------------------------------------------------

If using the taxonomy system proves too difficult, we will have to fall back on generating
indexes separately.
As at present, this will be driven from `.bib` files.

* Journal indexes are to be produced from metadata held in `.bib` files.
* There will be one `.bib` file per journal.
* `.bib` files to be stored at `journal/<journal name>/<journal name>.bib`.

== Restricting access

The Conference website is similarly the product of a static site generator.
It uses a small https://www.fullstackpython.com/flask.html[Flask] module
to check if login is required and to handle the login.
It would seem sensible to adopt a similar solution.

For the immediate future, this would have to use the existing Xaraya membership database.
At some point in the future, when all but that part of Xaraya has been replaced,
I would be looking to move to some off-the-shelf membership management system.
We should not be having to code for payment processors ourselves.
