#!/usr/bin/python3
#
# accu-xml-tool [--html] [--adoc] XML/HTML file
#
# Convert an input HTML or XML file in ACCU style to AsciiDoc
# (the default) or HTML.

import argparse
import re
import sys

import bs4

import accuwebsite

def main():
    parser = argparse.ArgumentParser(description='convert ACCU XML/HTML to AsciiDoc or HTML.')
    parser.add_argument('--input-format', dest='input_format', action='store',
                        choices=['html', 'xml'], default='xml',
                        help='input format - html or xml', metavar='FORMAT')
    parser.add_argument('--output-format', dest='output_format', action='store',
                        choices=['html', 'adoc'], default='adoc',
                        help='output format - adoc or html', metavar='FORMAT')
    parser.add_argument('-t', '--title', dest='title',
                        action='store', default='(No title)',
                        help='article title', metavar='TITLE')
    parser.add_argument('-a', '--author', dest='author',
                        action='store', default=None,
                        help='article author', metavar='AUTHOR')
    parser.add_argument('-s', '--summary', dest='summary',
                        action='store', default=None,
                        help='article summary', metavar='SUMMARY')
    parser.add_argument('-b', '--include-bio', dest='includebio',
                        action='store_true',
                        help='include author bio, if present')
    parser.add_argument('input', type=argparse.FileType('r'),
                        help='input XML or HTML file',
                        metavar='XML/HTML file')
    args = parser.parse_args()

    try:
        text = accuwebsite.convert_article(args.input, args.input_format, args.output_format, args.title, args.author, args.summary, args.includebio)
        print(text)
        sys.exit(0)
    except accuwebsite.ConversionError as e:
        print(e, file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()

# Local Variables:
# mode: Python
# End:
